# Generated by Django 3.0.5 on 2020-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_brand', models.CharField(max_length=50)),
                ('bike_model', models.CharField(max_length=50)),
                ('production_year', models.IntegerField(max_length=4)),
                ('terrain_type', models.CharField(max_length=20)),
            ],
        ),
    ]
