# Generated by Django 3.0.5 on 2020-06-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_brand',
            field=models.CharField(max_length=20),
        ),
    ]
