# Generated by Django 3.0.5 on 2020-06-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200624_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='equipment',
            field=models.ManyToManyField(to='main_app.Equipment'),
        ),
    ]
